### ISSUE TITLE
Create Database documentation

### ISSUE THREAD

**Issue by tbellenger** [tbellenger/coding-bc-project-2#4]
Create a database documentation showing the different tables and their relationships
User
- Id
- Name
- Email
- Password
- Rating
- Jobs Completed
- Jobs Offered
- Last Login

Posting
- Id
- Title
- Description
- Payment offered
- Payment type offered
- Owner (User)
- Applicants (Users)
- Status (open, filled, complete)

Category
- Id
- Category Name - (Yard, Handyman, Plumbing, Paint, Indoor, Outdoor)
 
Zip Code????, 

Tag
- Id
- Tag Name

etc

**Comment by tarekyou** [comment]
not sure if payment method field should be multiple choices or string data type

**Comment by tbellenger** [comment]
I think payment method should be multiple. Like I can say I am happy to pay in cash, with cashapp, with venmo, with zelle, etc

**Comment by tbellenger** [comment]
Maybe we don't need a full document. Just bullet points like above?
